export default {
	wooden_shovel: 2.5,
	wooden_pickaxe: 3,
	wooden_axe: 4,
	wooden_sword: 6.4,
	golden_shovel: 2.5,
	golden_pickaxe: 3,
	golden_axe: 4,
	golden_sword: 6.4,
	stone_shovel: 3.5,
	stone_pickaxe: 4,
	stone_axe: 5,
	stone_sword: 8,
	iron_shovel: 4.5,
	iron_pickaxe: 5,
	iron_axe: 6,
	iron_sword: 9.6,
	diamond_shovel: 5.5,
	diamond_pickaxe: 6,
	diamond_axe: 7,
	diamond_sword: 11.2
};
